### ISSUE TITLE
Server crashing after adding Bloodlines (NeoForge 1.21.1)

### ISSUE THREAD

**Issue by gamerpotion** [TheDrOfDoctoring/bloodlines#1]
Hi, I recently added Bloodlines to my Vagrant Saga modpack - https://legacy.curseforge.com/minecraft/modpacks/vagrant-saga
on an existing server this seems to be causing the entire server to crash when players join 
crash log - https://pastebin.com/ZA4hbjDi

**Comment by TheDrOfDoctoring** [comment]
oops - accidentally used the narrator import. should be fixed in the [latest release](https://legacy.curseforge.com/minecraft/mc-mods/bloodlines/files/5822357).
